name: Ratedly
description: A new Flutter project.
version: 1.0.15+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  provider: ^6.0.1
  uuid: ^4.5.1
  cached_network_image: ^3.3.0
  timeago: ^3.7.0
  path_provider: ^2.1.1
  image: ^4.0.17
  flutter_image_compress: ^2.0.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  firebase_analytics: ^11.5.0
  flutter_native_splash: ^2.3.10
  google_sign_in: ^6.1.11
  sign_in_with_apple: ^7.0.1
  supabase_flutter: ^2.9.1
  google_mobile_ads: ^6.0.0
  video_player: ^2.8.2
  video_trimmer: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2



flutter:
  uses-material-design: true

  assets:
    - assets/logo/22.png
    - assets/logo/google-logo.png
    - assets/logo/apple-logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
